# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    #Setup java
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Checkout our code
      uses: actions/checkout@v2
      
     #Make gradlew executable
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    #Run our build using Gradle
    - name: Build with Gradle
      run: ./gradlew build
    
    #Run the TestNG tests.
    - name: Run TestNG tests
      run: ./gradlew test
    
    # Create Scan Report 
    - name: Build with Gradle creating Scan 
      run: ./gradlew clean build --scan --no-daemon